language: rust
cache: cargo
rust:
  - stable
  - nightly
env:
  - TRAVIS_CARGO_FEATURES=
  - TRAVIS_CARGO_FEATURES="zcstream"
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - ./.travis-helper.sh "${TRAVIS_CARGO_FEATURES}"
